<?php

/**
 * Scheduler will call this function to email all users who's orders were
 * completed 7 days ago to ask them to review their products.
 */

function qsn_tweaks_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'webform_client_form_13'){
    $form['submitted']['email']['#attributes']['placeholder'] = array('your.address@email.com');
    $form['submitted']['fullname']['#attributes']['placeholder'] = array('your name');
  }

  if (strpos($form_id,'commerce_cart_add_to_cart_form') !== false) {
    $form['submit']['#attributes'] = array('class' => array('col-md-6 col-sm-6'));
  }

  if($form_id == 'views_form_commerce_cart_form_default'){
    $form['modal_popup'] = array(
      '#prefix' => '<div class="modal fade" id="qsnModal" tabindex="-1" role="dialog" aria-labelledby="qsnModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="qsnModalLabel">Quit Stop Now - please answer the following before proceeding</h4>
                      </div>',
        '#suffix' => '</div>
                  </div>
                </div>',
    );

  $form['modal_popup']['content']['top'] = array(
    '#prefix' => '<div class="modal-body">',
    '#suffix' => '</div>',
  );
  $form['modal_popup']['content']['top']['q1'] = array(
    '#title' => t('This is question 1'),
    '#type' => 'checkboxes',
    '#options' => array(1 => 'Yes', 0 => 'No'),
  );
  $form['modal_popup']['content']['top']['q2'] = array(
    '#title' => t('This is question 2'),
    '#type' => 'checkboxes',
    '#options' => array(1 => 'Yes', 0 => 'No'),
  );
  $form['modal_popup']['content']['top']['q3'] = array(
    '#title' => t('This is question 3'),
    '#type' => 'checkboxes',
    '#options' => array(1 => 'Yes', 0 => 'No'),
  );
  $form['modal_popup']['content']['top']['q4'] = array(
    '#title' => t('This is question 4'),
    '#type' => 'checkboxes',
    '#options' => array(1 => 'Yes', 0 => 'No'),
  );
  $form['modal_popup']['content']['top']['q5'] = array(
    '#title' => t('This is question 5'),
    '#type' => 'checkboxes',
    '#options' => array(1 => 'Yes', 0 => 'No'),
  );
  $form['modal_popup']['content']['bottom'] = array(
    '#prefix' => '<div class="modal-footer">',
    '#suffix' => '</div>',
  );

  $form['modal_popup']['content']['bottom']['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
    '#attributes' => array('id' => array('submit-the-modal')),
  );

  $form['actions']['checkout']['#attributes'] = array(
    'data-toggle' => 'modal',
    'data-target' => '#qsnModal'
  );
  unset($form['actions']['checkout']['#submit']);
  unset($form['#submit']);
  $form['actions']['checkout']['#submit'][] = 'qsn_tweaks_checkout_form_submit';
  $form['#submit'][] = 'qsn_tweaks_checkout_form_submit';
  // dpm($form);

// <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#qsnModal">
//   Launch demo modal
// </button>
  }
}

function qsn_tweaks_checkout_form_submit(&$form, &$form_state){
  // drupal_set_message('hello');
  // dpm($form_state);
  if($form_state['values']['q1'][0] == 1){

  }
}

// /**
// * Implements hook_theme_registry_alter().
// */
// function pleatz_tweaks_theme_registry_alter(&$theme_registry) {
//   // Remove cart block total label & add cart link on item.
//   $theme_registry['commerce_line_item_summary']['path'] = drupal_get_path('module', 'pleatz_tweaks') . '/theme';
//   $theme_registry['commerce_line_item_summary']['template'] = 'commerce-line-item-summary';
// }

// /**
// * Implements hook_preprocess_HOOK().
// * Link cart block items to cart.
// */
// function pleatz_tweaks_preprocess_commerce_line_item_summary(&$variable) {
//   $variable['cart_items'] = l($variable['quantity'], 'cart', array('attributes' => array('class' => array('line-item-quantity'))));
// }

/**
* Implements hook_entity_info_alter().
*/
// function pleatz_tweaks_entity_info_alter(&$entity_info) {
//   $entity_info['node']['view modes']['pleatz_search_result'] = array(
//     'label' => t('Pleatz Search Result'),
//     'custom settings' => TRUE,
//   );
// }

// // Custom rules actions for pleatz
// function pleatz_tweaks_rules_action_info() {
//   $actions['pleatz_allocate_orders_to_suppliers'] = array(
//     'label' => t('Pleatz allocate orders to suppliers'),
//     'parameter' => array(
//       'commerce_order' => array(
//         'type' => 'commerce_order',
//         'label' => t('orders'),
//       ),
//     ),
//     'group' => t('pleatz - actions'),
//     'callbacks' => array(
//       'execute' => 'pleatz_allocate_orders_to_suppliers',
//     ),
//     'provides' => array(
//       'suppliers_info' => array(
//         'label' => t('Suppliers'),
//         'type' => 'list',
//       ),
//     ),
//   );
//   return $actions;
// }







